import type { AssignmentResponse, BlueprintSpec, PersonaId } from "./types";

export const PERSONAS: PersonaId[] = ["scanner", "comparer", "explorer", "expert_operator"];

export function isPersona(value: unknown): value is PersonaId {
  return typeof value === "string" && PERSONAS.includes(value as PersonaId);
}

export const fallbackSpec: BlueprintSpec = {
  schema_version: "flightdeck.blueprint.v1",
  persona_id: "scanner",
  surface_id: "event_discovery",
  catalog_version: "flightdeck-event-discovery-v1",
  design_md_hash: "sha256:fallback",
  hypothesis: "Fallback UI preserves the current event discovery experience.",
  primary_metric: "first_action_rate",
  layout: "filters_left",
  expected_first_action: "buy_tickets",
  filters: {
    type: "filters",
    title: "Filters",
    search_label: "Search",
    search_placeholder: "Event name...",
    categories: ["Concerts", "Conferences", "Talks", "Theater", "Sports", "Festivals"],
    selected_categories: ["Concerts"],
    areas: ["Downtown", "Wynwood", "South Beach", "Brickell", "Coconut Grove"],
    selected_area: "Downtown",
    date_options: ["Today", "This week", "This month", "Custom"],
    max_price: 250,
    primary_action_label: "Apply filters",
  },
  event_list: {
    type: "event_list",
    title: "Discover amazing events",
    summary: "5 events found in Miami",
    sort_options: ["Most relevant", "Upcoming", "Price: low to high"],
    default_sort: "Most relevant",
    density: "comfortable",
    event_order: ["bad-bunny", "reactconf", "simplicity-talk", "ultra", "standup-night"],
    primary_action_label: "Buy tickets",
  },
  events: [
    {
      id: "bad-bunny",
      title: "Bad Bunny - Most Wanted Tour",
      category: "Concert",
      date: "Sat, Jun 14 - 9:00 PM",
      area: "Downtown Miami",
      venue: "Kaseya Center",
      price: "From $120",
      attending: "12.4k",
      gradient: "from-fuchsia-500 via-violet-500 to-indigo-500",
      emoji: "🎤",
    },
    {
      id: "reactconf",
      title: "ReactConf US 2026",
      category: "Conference",
      date: "Thu, Jul 3 - 8:30 AM",
      area: "Brickell",
      venue: "Miami Convention Center",
      price: "From $95",
      attending: "1.8k",
      gradient: "from-cyan-400 via-sky-500 to-blue-600",
      emoji: "💻",
    },
    {
      id: "simplicity-talk",
      title: "Talk: The Art of Simplicity",
      category: "Talk",
      date: "Fri, May 22 - 7:00 PM",
      area: "Coconut Grove",
      venue: "Coconut Grove Playhouse",
      price: "From $35",
      attending: "640",
      gradient: "from-amber-400 via-orange-500 to-rose-500",
      emoji: "🎭",
    },
    {
      id: "ultra",
      title: "Ultra Music Festival",
      category: "Festival",
      date: "Fri, Mar 27 - 2:00 PM",
      area: "Downtown Miami",
      venue: "Bayfront Park",
      price: "From $320",
      attending: "45k",
      gradient: "from-emerald-400 via-teal-500 to-cyan-600",
      emoji: "🎶",
    },
    {
      id: "standup-night",
      title: "Standup Night - Trevor Noah",
      category: "Talk",
      date: "Sat, May 31 - 8:30 PM",
      area: "South Beach",
      venue: "Fillmore Miami Beach",
      price: "From $60",
      attending: "1.2k",
      gradient: "from-pink-400 via-rose-500 to-red-500",
      emoji: "🎙️",
    },
  ],
};

export function fallbackAssignment(persona: PersonaId): AssignmentResponse {
  const spec = { ...fallbackSpec, persona_id: persona };
  return {
    experiment: {
      id: "fallback_experiment",
      surface_id: "event_discovery",
      name: "Fallback Event Discovery",
      hypothesis: spec.hypothesis,
      primary_metric: spec.primary_metric,
      status: "active",
      created_at: "",
      updated_at: "",
      variants: [],
      metrics: {},
    },
    variant: {
      id: "fallback_variant",
      experiment_id: "fallback_experiment",
      blueprint_id: "fallback_blueprint",
      persona_id: persona,
      surface_id: "event_discovery",
      status: "active",
      expected_first_action: spec.expected_first_action,
      guardrail_status: "passed",
      created_at: "",
      activated_at: null,
    },
    blueprint: {
      id: "fallback_blueprint",
      persona_id: persona,
      surface_id: "event_discovery",
      status: "validated",
      spec,
      critique: {
        status: "passed",
        checks: {},
        summary: "Static fallback assignment.",
      },
      catalog_version: spec.catalog_version,
      design_md_hash: spec.design_md_hash,
      created_at: "",
    },
  };
}
